#!/bin/env bash

USAGE=",-----.  ,------.,------.,--------.,--.
|  |) /_ |  .---'|  .---''--.  .--'|  |   
|  .-.  \|  \`--, |  \`--,    |  |   |  |   
|  '--' /|  \`---.|  \`---.   |  |   |  '--.
\`------' \`------'\`------'   \`--'   \`-----'
Version 0.1.0

Usage: beetl [--version] [--help] <COMMAND> [ARGS]

Available commands:
    bwt       Encode a set of nucleotide sequences using Burrows-Wheeler transform
    unbwt     Decode nucleotide sequences dataset from its BWT
    convert   Convert between file formats
    search    Search within a BWT dataset
    compare   Compare two BWT datasets

View sub-commands with:
    beetl <COMMAND> --help
"

VERSION="BEETL v0.1.0"

ABS_COMMAND="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
ABS_PATH=`dirname "${ABS_COMMAND}"`


if [ "$#" == "0" ]; then
  echo "${USAGE}" 
  exit 1
fi

KEYWORD=$1

# Convert aliases: encode->bwt, decode->unbwt
case "${KEYWORD}" in

  encode)
    KEYWORD="bwt"
    ;;

  decode)
    KEYWORD="unbwt"
    ;;

esac

# Jump table
case "${KEYWORD}" in

  --version|version)
    echo "${VERSION}"
    ;;

  --help|help)
    echo "${USAGE}"
    ;;

  *)
    TOOL="${ABS_COMMAND}-${KEYWORD}"
    if [ -x "${TOOL}" ]; then
        shift
        COMMAND="${TOOL} $*"
        #echo "Launching: ${COMMAND}"
        ${COMMAND}
    else
        echo "Error: Invalid command \"${KEYWORD}\""
        echo "${USAGE}"
        exit 1
    fi
    ;;

esac
